# Generated by Django 4.2.8 on 2025-05-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0005_taskproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='color',
            field=models.CharField(choices=[('#ffc107', 'Vàng'), ('#28a745', 'Xanh lá'), ('#17a2b8', 'Xanh dương'), ('#dc3545', 'Đỏ'), ('#6f42c1', 'Tím')], default='#ffc107', max_length=7),
        ),
    ]
