# Generated by Django 4.2.8 on 2025-05-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0006_todolist_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
