# Generated by Django 4.2.8 on 2025-05-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mxh', '0007_alter_todolist_options_todolist_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='position',
        ),
    ]
